# Site settings
title: 翰林苑
SEOTitle: "翰林苑 | 董翰林的个人网站"
# header-img: img/home-bg.jpg
email: hanlin.dong@gmail.com
description: "董翰林的个人网站，同济土木结构工程专业，提供在线结构工具，和结构工程相关资源下载。"
keyword: "董翰林, 同济土木, 结构工具, opensees"
url: "https://www.hanlindong.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
pinterest_username: hanlindong
#weibo_username:     ShearTheMoment
#zhihu_username:     董木木
github_username:    hanlin-dong
facebook_username:  "hanlin.dong.tj"
linkedin_username:  hanlin-dong-9267ba4b
researchgate_username: Hanlin_Dong



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.


permalink: /:year/:title/
paginate: 10
exclude: ["renewruls.txt", "urls.txt"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`

markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# markdown: kramdown
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "潦倒不通事物，愚顽怕读文章。<br>天下无能第一，古今不肖无双。"
sidebar-avatar: /img/avatar-hanlin.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value




# Friends
friends: [
    {
        title: "小同人",
        href: "https://mp.weixin.qq.com/s?__biz=MzIxMzI5MzgyNg==&mid=2247483702&idx=1&sn=daea7b8132ffafff11df67532165b98e&scene=27#wechat_redirect"
    },
    {
        title: "Wonderworks",
        href: "https://mp.weixin.qq.com/s?__biz=MzAwMTcwMDg5MA==&mid=208299309&idx=1&sn=4685f66683a9aed5de31cc59ea9b8bff&chksm=134b6058243ce94e9567d6b906699301c776a69d3a0d48dda34870dc3126ec44449f2004373f&mpshare=1&scene=1&srcid=0426V3UGfCpAyh7YvNvTV9Ys&key=7a29a072f4e2e9e620ef50acb56c85da13fa3b2278af80cba91afd48847321c13b44cc7f703a1e64c9c699f1d65b38d1284c74f5e78d7141e6b9687dcb443349df728639043e2eef6a592152d16c5857&ascene=0&uin=NzY5ODEwODQw&devicetype=iMac+MacBook9%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=5WFS2wE9kkzkH2zWPMC6ZC7izXm3uq1jlv7KqzaPb3eElfuoJDK6Adopytm5Bxgo"
    },
    {
        title: "娴言绿语",
        href: "https://mp.weixin.qq.com/s?__biz=MzI5NDI2NTY2NQ==&mid=100000011&idx=1&sn=d985386d0e874781c41bb7aca6927629&mpshare=1&scene=1&srcid=0422i4sOJMJ4btS7MP5JSugL&key=ef3ba97d86256e846addc26efd23ab3e648a6b451aed0a869ab1a659d1bfe9690ea2b177273ec7f0bd8684567ac02990823f2f96eec98db33ef2b6eeed72090e3d843d59eef8e521e737605b978d3230&ascene=0&uin=NzY5ODEwODQw&devicetype=iMac+MacBook9%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=bufH1M6r3g1A8EZHIjv3zd4hziDN0GB4%2Bf4O2i1Rm2ifaJUUQEBgW6FhRsord3W6"
    },
    {
        title: "亚力克斯祝",
        href: "https://mp.weixin.qq.com/s?__biz=MzIzNjc2MTkyOA==&mid=2247483751&idx=1&sn=0bae83a78f305c84225d45d21affc76b&chksm=e8d3a740dfa42e567363e3a712ef4e22ff327b459dee35370d0a056c42e66562aa85662c8736&mpshare=1&scene=1&srcid=0422s2SCWuyeJCmuCE71uKoP&key=d054b2c1269a6c2e9290eddf2ff6c4ff79935354bbb7745beb765f7e7449c973463e702efde43158c54064cde5b18c3e98189b61b000f4936750463ecc8ca3be5b020b8aff1fe2afad952edc646f2d7f&ascene=0&uin=NzY5ODEwODQw&devicetype=iMac+MacBook9%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=bufH1M6r3g1A8EZHIjv3zd4hziDN0GB4%2Bf4O2i1Rm2ifaJUUQEBgW6FhRsord3W6"
    },
    {
        title: "Pullweeds",
        href: "https://mp.weixin.qq.com/s?__biz=MzA3NDU2MTg1MA==&mid=400944428&idx=1&sn=8f7284bc5503cca8dbab94198ecb212b&mpshare=1&scene=1&srcid=0426lGZpytExa75zHA5CA5ui&key=6573c25d21514e33be33c335afd159a79fb87df61e83b493558d2b1c231b594eb05c62ceeeb46ee18ca10742cd76e4226a57eddccb9b1678eae895e522903415f7307136075e86974cca5e4b430e51f6&ascene=0&uin=NzY5ODEwODQw&devicetype=iMac+MacBook9%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=5WFS2wE9kkzkH2zWPMC6ZC7izXm3uq1jlv7KqzaPb3eElfuoJDK6Adopytm5Bxgo"
    },
    {
        title: "小诗弹记",
        href: "https://mp.weixin.qq.com/s?__biz=MzIwNjgwODIwOA==&mid=2247483670&idx=1&sn=77a20c6f90e7dece8f8652f1cbfdb10b&chksm=971ab4e9a06d3dff523d357a0c05f30e06805a96df6f24d1f07ebb1a442ea4eeb39487b5fd11&mpshare=1&scene=1&srcid=0422zmkegOMHx7NtU7ESCQYt&key=5099feb8a76f6ef0eca1524a8ea32e9390c6dd0e1e648a382aee14975163902440c092c91563eabcbf30050fe064c4d31301a215724a6be89db4f62300c15591a16e194b9db173d64561d5d6b5f78dbe&ascene=0&uin=NzY5ODEwODQw&devicetype=iMac+MacBook9%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=bufH1M6r3g1A8EZHIjv3zd4hziDN0GB4%2Bf4O2i1Rm2ifaJUUQEBgW6FhRsord3W6"
    }
]

